name: teriprojekt
description: "Recepty Terinky"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  collection: ^1.19.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/seeds/default_ingredients_v1.json
    - assets/branding/logo_wordmark.png
    - assets/branding/app_icon_1024.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/app_icon_1024.png
  remove_alpha_ios: true
