class IngredientNameFormatter {
  static const Map<String, String> _fullNames = {
    'ajvar': 'Ajvar',
    'agar': 'Agar',
    'ananas': 'Ananas',
    'avokado': 'Avokádo',
    'banan': 'Banán',
    'brokolice': 'Brokolice',
    'bulgur': 'Bulgur',
    'celer': 'Celer',
    'cibule': 'Cibule',
    'citron': 'Citron',
    'cuketa': 'Cuketa',
    'cukr': 'Cukr',
    'dyne': 'Dýně',
    'jahody': 'Jahody',
    'jogurt bily': 'Jogurt bílý',
    'kakao': 'Kakao',
    'kapary': 'Kapary',
    'kedlubna': 'Kedlubna',
    'kimchi': 'Kimchi',
    'kopr': 'Kopr',
    'kuskus': 'Kuskus',
    'losos': 'Losos',
    'majoranka': 'Majoránka',
    'mak': 'Mák',
    'mango': 'Mango',
    'mascarpone': 'Mascarpone',
    'maslo': 'Máslo',
    'med': 'Med',
    'mleko': 'Mléko',
    'okurka': 'Okurka',
    'olivovy olej': 'Olivový olej',
    'oregano': 'Oregano',
    'paprika': 'Paprika',
    'parmazan': 'Parmazán',
    'pazitka': 'Pažitka',
    'petrzel': 'Petržel',
    'quinoa': 'Quinoa',
    'rajcata': 'Rajčata',
    'rukola': 'Rukola',
    'slanina': 'Slanina',
    'slehacka': 'Šlehačka',
    'smetana na vareni': 'Smetana na vaření',
    'sol': 'Sůl',
    'spenat': 'Špenát',
    'strouhanka': 'Strouhanka',
    'taveny syr': 'Tavený sýr',
    'tofu': 'Tofu',
    'tortilla': 'Tortilla',
    'tvaroh': 'Tvaroh',
    'vejce': 'Vejce',
    'voda': 'Voda',
    'zampiony': 'Žampiony',
    'zazvor': 'Zázvor',
  };

  static const Map<String, String> _tokens = {
    'arasidove': 'arašídové',
    'ananasovy': 'ananasový',
    'avokado': 'avokádo',
    'bila': 'bílá',
    'bile': 'bílé',
    'bily': 'bílý',
    'brambory': 'brambory',
    'bujon': 'bujón',
    'cesnek': 'česnek',
    'cesnekovy': 'česnekový',
    'cervena': 'červená',
    'cervene': 'červené',
    'cerveny': 'červený',
    'cibulka': 'cibulka',
    'cocka': 'čočka',
    'cokolada': 'čokoláda',
    'cukr': 'cukr',
    'dyne': 'dýně',
    'fazole': 'fazole',
    'grilovaci': 'grilovací',
    'hrasek': 'hrášek',
    'hovezi': 'hovězí',
    'jarni': 'jarní',
    'jemny': 'jemný',
    'jogurt': 'jogurt',
    'kapr': 'kapr',
    'kari': 'kari',
    'kesu': 'kešu',
    'kmín': 'kmín',
    'koreni': 'koření',
    'kruti': 'krůtí',
    'kure': 'kuře',
    'kureci': 'kuřecí',
    'kysane': 'kysané',
    'kysele': 'kyselé',
    'kyprici': 'kypřicí',
    'lzice': 'lžíce',
    'lzicka': 'lžička',
    'makky': 'měkký',
    'mandlove': 'mandlové',
    'maslo': 'máslo',
    'mleko': 'mléko',
    'mleta': 'mletá',
    'mlete': 'mleté',
    'mlety': 'mletý',
    'mouka': 'mouka',
    'moucka': 'moučka',
    'nadobi': 'nádobí',
    'nakladane': 'nakládané',
    'oblibene': 'oblíbené',
    'okurka': 'okurka',
    'olej': 'olej',
    'olivovy': 'olivový',
    'omacka': 'omáčka',
    'orechy': 'ořechy',
    'ovesne': 'ovesné',
    'paprika': 'paprika',
    'pazitka': 'pažitka',
    'peceni': 'pečení',
    'pikantni': 'pikantní',
    'polevove': 'polévkové',
    'polotucne': 'polotučné',
    'polotucny': 'polotučný',
    'pomazanka': 'pomazánka',
    'pomeranc': 'pomeranč',
    'poznámka': 'poznámka',
    'pseno': 'pšeno',
    'rajcata': 'rajčata',
    'rejze': 'rýže',
    'rejzova': 'rýžová',
    'rozmaryn': 'rozmarýn',
    'ruzove': 'růžové',
    'ryzove': 'rýžové',
    'smetana': 'smetana',
    'snezne': 'sněžné',
    'sol': 'sůl',
    'suseny': 'sušený',
    'susene': 'sušené',
    'susena': 'sušená',
    'syr': 'sýr',
    'stava': 'šťáva',
    'svestky': 'švestky',
    'taveny': 'tavený',
    'testoviny': 'těstoviny',
    'treba': 'třeba',
    'treska': 'treska',
    'tvaroh': 'tvaroh',
    'tvrdy': 'tvrdý',
    'tymian': 'tymián',
    'uherak': 'uherák',
    'uzena': 'uzená',
    'uzene': 'uzené',
    'uzeny': 'uzený',
    'vanilka': 'vanilka',
    'vareni': 'vaření',
    'veprove': 'vepřové',
    'veprova': 'vepřová',
    'veprovy': 'vepřový',
    'vlasske': 'vlašské',
    'vlakna': 'vlákna',
    'vyvar': 'vývar',
    'zampiony': 'žampiony',
    'zazvor': 'zázvor',
    'zelena': 'zelená',
    'zelene': 'zelené',
    'zeleny': 'zelený',
  };

  static String prettify(String raw) {
    final trimmed = raw.trim();
    if (trimmed.isEmpty) {
      return trimmed;
    }

    final full = _fullNames[trimmed.toLowerCase()];
    if (full != null) {
      return full;
    }

    final words = trimmed.split(' ');
    final converted = words.map((word) {
      final lower = word.toLowerCase();
      return _tokens[lower] ?? word;
    }).toList();
    final result = converted.join(' ');
    return result[0].toUpperCase() + result.substring(1);
  }
}
